//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace WebAppTestWebService.th.co.lmginsurance.ebizuat {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WSGetMakeOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGetMakeYearOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGetModelOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGetModelDescriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGetCarInsuredAVOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGetMotorCodeACOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGetProvinceAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGetAmphurAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGetTumbonAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGetProvinceLicenseOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGetBeneficiaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGetCountryOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSGetMotorCodeAVACOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::WebAppTestWebService.Properties.Settings.Default.WebAppTestWebService_th_co_lmginsurance_ebizuat_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WSGetMakeCompletedEventHandler WSGetMakeCompleted;
        
        /// <remarks/>
        public event WSGetMakeYearCompletedEventHandler WSGetMakeYearCompleted;
        
        /// <remarks/>
        public event WSGetModelCompletedEventHandler WSGetModelCompleted;
        
        /// <remarks/>
        public event WSGetModelDescriptionCompletedEventHandler WSGetModelDescriptionCompleted;
        
        /// <remarks/>
        public event WSGetCarInsuredAVCompletedEventHandler WSGetCarInsuredAVCompleted;
        
        /// <remarks/>
        public event WSGetMotorCodeACCompletedEventHandler WSGetMotorCodeACCompleted;
        
        /// <remarks/>
        public event WSGetProvinceAddressCompletedEventHandler WSGetProvinceAddressCompleted;
        
        /// <remarks/>
        public event WSGetAmphurAddressCompletedEventHandler WSGetAmphurAddressCompleted;
        
        /// <remarks/>
        public event WSGetTumbonAddressCompletedEventHandler WSGetTumbonAddressCompleted;
        
        /// <remarks/>
        public event WSGetProvinceLicenseCompletedEventHandler WSGetProvinceLicenseCompleted;
        
        /// <remarks/>
        public event WSGetBeneficiaryCompletedEventHandler WSGetBeneficiaryCompleted;
        
        /// <remarks/>
        public event WSGetCountryCompletedEventHandler WSGetCountryCompleted;
        
        /// <remarks/>
        public event WSGetMotorCodeAVACCompletedEventHandler WSGetMotorCodeAVACCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetMake", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetMake(string ac_only) {
            object[] results = this.Invoke("WSGetMake", new object[] {
                        ac_only});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetMakeAsync(string ac_only) {
            this.WSGetMakeAsync(ac_only, null);
        }
        
        /// <remarks/>
        public void WSGetMakeAsync(string ac_only, object userState) {
            if ((this.WSGetMakeOperationCompleted == null)) {
                this.WSGetMakeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetMakeOperationCompleted);
            }
            this.InvokeAsync("WSGetMake", new object[] {
                        ac_only}, this.WSGetMakeOperationCompleted, userState);
        }
        
        private void OnWSGetMakeOperationCompleted(object arg) {
            if ((this.WSGetMakeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetMakeCompleted(this, new WSGetMakeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetMakeYear", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetMakeYear(string ac_only, string car_brand_value) {
            object[] results = this.Invoke("WSGetMakeYear", new object[] {
                        ac_only,
                        car_brand_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetMakeYearAsync(string ac_only, string car_brand_value) {
            this.WSGetMakeYearAsync(ac_only, car_brand_value, null);
        }
        
        /// <remarks/>
        public void WSGetMakeYearAsync(string ac_only, string car_brand_value, object userState) {
            if ((this.WSGetMakeYearOperationCompleted == null)) {
                this.WSGetMakeYearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetMakeYearOperationCompleted);
            }
            this.InvokeAsync("WSGetMakeYear", new object[] {
                        ac_only,
                        car_brand_value}, this.WSGetMakeYearOperationCompleted, userState);
        }
        
        private void OnWSGetMakeYearOperationCompleted(object arg) {
            if ((this.WSGetMakeYearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetMakeYearCompleted(this, new WSGetMakeYearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetModel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetModel(string ac_only, string car_brand_value, string regis_year_value) {
            object[] results = this.Invoke("WSGetModel", new object[] {
                        ac_only,
                        car_brand_value,
                        regis_year_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetModelAsync(string ac_only, string car_brand_value, string regis_year_value) {
            this.WSGetModelAsync(ac_only, car_brand_value, regis_year_value, null);
        }
        
        /// <remarks/>
        public void WSGetModelAsync(string ac_only, string car_brand_value, string regis_year_value, object userState) {
            if ((this.WSGetModelOperationCompleted == null)) {
                this.WSGetModelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetModelOperationCompleted);
            }
            this.InvokeAsync("WSGetModel", new object[] {
                        ac_only,
                        car_brand_value,
                        regis_year_value}, this.WSGetModelOperationCompleted, userState);
        }
        
        private void OnWSGetModelOperationCompleted(object arg) {
            if ((this.WSGetModelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetModelCompleted(this, new WSGetModelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetModelDescription", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetModelDescription(string ac_only, string car_brand_value, string regis_year_value, string car_model_value) {
            object[] results = this.Invoke("WSGetModelDescription", new object[] {
                        ac_only,
                        car_brand_value,
                        regis_year_value,
                        car_model_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetModelDescriptionAsync(string ac_only, string car_brand_value, string regis_year_value, string car_model_value) {
            this.WSGetModelDescriptionAsync(ac_only, car_brand_value, regis_year_value, car_model_value, null);
        }
        
        /// <remarks/>
        public void WSGetModelDescriptionAsync(string ac_only, string car_brand_value, string regis_year_value, string car_model_value, object userState) {
            if ((this.WSGetModelDescriptionOperationCompleted == null)) {
                this.WSGetModelDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetModelDescriptionOperationCompleted);
            }
            this.InvokeAsync("WSGetModelDescription", new object[] {
                        ac_only,
                        car_brand_value,
                        regis_year_value,
                        car_model_value}, this.WSGetModelDescriptionOperationCompleted, userState);
        }
        
        private void OnWSGetModelDescriptionOperationCompleted(object arg) {
            if ((this.WSGetModelDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetModelDescriptionCompleted(this, new WSGetModelDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetCarInsuredAV", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetCarInsuredAV(string car_brand_value, string regis_year_value, string car_model_value, string sub_model_value) {
            object[] results = this.Invoke("WSGetCarInsuredAV", new object[] {
                        car_brand_value,
                        regis_year_value,
                        car_model_value,
                        sub_model_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetCarInsuredAVAsync(string car_brand_value, string regis_year_value, string car_model_value, string sub_model_value) {
            this.WSGetCarInsuredAVAsync(car_brand_value, regis_year_value, car_model_value, sub_model_value, null);
        }
        
        /// <remarks/>
        public void WSGetCarInsuredAVAsync(string car_brand_value, string regis_year_value, string car_model_value, string sub_model_value, object userState) {
            if ((this.WSGetCarInsuredAVOperationCompleted == null)) {
                this.WSGetCarInsuredAVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetCarInsuredAVOperationCompleted);
            }
            this.InvokeAsync("WSGetCarInsuredAV", new object[] {
                        car_brand_value,
                        regis_year_value,
                        car_model_value,
                        sub_model_value}, this.WSGetCarInsuredAVOperationCompleted, userState);
        }
        
        private void OnWSGetCarInsuredAVOperationCompleted(object arg) {
            if ((this.WSGetCarInsuredAVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetCarInsuredAVCompleted(this, new WSGetCarInsuredAVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetMotorCodeAC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetMotorCodeAC(string car_brand_value, string car_model_value) {
            object[] results = this.Invoke("WSGetMotorCodeAC", new object[] {
                        car_brand_value,
                        car_model_value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetMotorCodeACAsync(string car_brand_value, string car_model_value) {
            this.WSGetMotorCodeACAsync(car_brand_value, car_model_value, null);
        }
        
        /// <remarks/>
        public void WSGetMotorCodeACAsync(string car_brand_value, string car_model_value, object userState) {
            if ((this.WSGetMotorCodeACOperationCompleted == null)) {
                this.WSGetMotorCodeACOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetMotorCodeACOperationCompleted);
            }
            this.InvokeAsync("WSGetMotorCodeAC", new object[] {
                        car_brand_value,
                        car_model_value}, this.WSGetMotorCodeACOperationCompleted, userState);
        }
        
        private void OnWSGetMotorCodeACOperationCompleted(object arg) {
            if ((this.WSGetMotorCodeACCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetMotorCodeACCompleted(this, new WSGetMotorCodeACCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetProvinceAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetProvinceAddress(string language) {
            object[] results = this.Invoke("WSGetProvinceAddress", new object[] {
                        language});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetProvinceAddressAsync(string language) {
            this.WSGetProvinceAddressAsync(language, null);
        }
        
        /// <remarks/>
        public void WSGetProvinceAddressAsync(string language, object userState) {
            if ((this.WSGetProvinceAddressOperationCompleted == null)) {
                this.WSGetProvinceAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetProvinceAddressOperationCompleted);
            }
            this.InvokeAsync("WSGetProvinceAddress", new object[] {
                        language}, this.WSGetProvinceAddressOperationCompleted, userState);
        }
        
        private void OnWSGetProvinceAddressOperationCompleted(object arg) {
            if ((this.WSGetProvinceAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetProvinceAddressCompleted(this, new WSGetProvinceAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetAmphurAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetAmphurAddress(string language, string province_code) {
            object[] results = this.Invoke("WSGetAmphurAddress", new object[] {
                        language,
                        province_code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetAmphurAddressAsync(string language, string province_code) {
            this.WSGetAmphurAddressAsync(language, province_code, null);
        }
        
        /// <remarks/>
        public void WSGetAmphurAddressAsync(string language, string province_code, object userState) {
            if ((this.WSGetAmphurAddressOperationCompleted == null)) {
                this.WSGetAmphurAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetAmphurAddressOperationCompleted);
            }
            this.InvokeAsync("WSGetAmphurAddress", new object[] {
                        language,
                        province_code}, this.WSGetAmphurAddressOperationCompleted, userState);
        }
        
        private void OnWSGetAmphurAddressOperationCompleted(object arg) {
            if ((this.WSGetAmphurAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetAmphurAddressCompleted(this, new WSGetAmphurAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetTumbonAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetTumbonAddress(string language, string province_code, string amphur_code) {
            object[] results = this.Invoke("WSGetTumbonAddress", new object[] {
                        language,
                        province_code,
                        amphur_code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetTumbonAddressAsync(string language, string province_code, string amphur_code) {
            this.WSGetTumbonAddressAsync(language, province_code, amphur_code, null);
        }
        
        /// <remarks/>
        public void WSGetTumbonAddressAsync(string language, string province_code, string amphur_code, object userState) {
            if ((this.WSGetTumbonAddressOperationCompleted == null)) {
                this.WSGetTumbonAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetTumbonAddressOperationCompleted);
            }
            this.InvokeAsync("WSGetTumbonAddress", new object[] {
                        language,
                        province_code,
                        amphur_code}, this.WSGetTumbonAddressOperationCompleted, userState);
        }
        
        private void OnWSGetTumbonAddressOperationCompleted(object arg) {
            if ((this.WSGetTumbonAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetTumbonAddressCompleted(this, new WSGetTumbonAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetProvinceLicense", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetProvinceLicense() {
            object[] results = this.Invoke("WSGetProvinceLicense", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetProvinceLicenseAsync() {
            this.WSGetProvinceLicenseAsync(null);
        }
        
        /// <remarks/>
        public void WSGetProvinceLicenseAsync(object userState) {
            if ((this.WSGetProvinceLicenseOperationCompleted == null)) {
                this.WSGetProvinceLicenseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetProvinceLicenseOperationCompleted);
            }
            this.InvokeAsync("WSGetProvinceLicense", new object[0], this.WSGetProvinceLicenseOperationCompleted, userState);
        }
        
        private void OnWSGetProvinceLicenseOperationCompleted(object arg) {
            if ((this.WSGetProvinceLicenseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetProvinceLicenseCompleted(this, new WSGetProvinceLicenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetBeneficiary", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetBeneficiary(string Beneficiary_Code, string Beneficiary_Name, string language) {
            object[] results = this.Invoke("WSGetBeneficiary", new object[] {
                        Beneficiary_Code,
                        Beneficiary_Name,
                        language});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetBeneficiaryAsync(string Beneficiary_Code, string Beneficiary_Name, string language) {
            this.WSGetBeneficiaryAsync(Beneficiary_Code, Beneficiary_Name, language, null);
        }
        
        /// <remarks/>
        public void WSGetBeneficiaryAsync(string Beneficiary_Code, string Beneficiary_Name, string language, object userState) {
            if ((this.WSGetBeneficiaryOperationCompleted == null)) {
                this.WSGetBeneficiaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetBeneficiaryOperationCompleted);
            }
            this.InvokeAsync("WSGetBeneficiary", new object[] {
                        Beneficiary_Code,
                        Beneficiary_Name,
                        language}, this.WSGetBeneficiaryOperationCompleted, userState);
        }
        
        private void OnWSGetBeneficiaryOperationCompleted(object arg) {
            if ((this.WSGetBeneficiaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetBeneficiaryCompleted(this, new WSGetBeneficiaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetCountry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetCountry(string language) {
            object[] results = this.Invoke("WSGetCountry", new object[] {
                        language});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetCountryAsync(string language) {
            this.WSGetCountryAsync(language, null);
        }
        
        /// <remarks/>
        public void WSGetCountryAsync(string language, object userState) {
            if ((this.WSGetCountryOperationCompleted == null)) {
                this.WSGetCountryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetCountryOperationCompleted);
            }
            this.InvokeAsync("WSGetCountry", new object[] {
                        language}, this.WSGetCountryOperationCompleted, userState);
        }
        
        private void OnWSGetCountryOperationCompleted(object arg) {
            if ((this.WSGetCountryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetCountryCompleted(this, new WSGetCountryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSGetMotorCodeAVAC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSGetMotorCodeAVAC(string motor_code_av) {
            object[] results = this.Invoke("WSGetMotorCodeAVAC", new object[] {
                        motor_code_av});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSGetMotorCodeAVACAsync(string motor_code_av) {
            this.WSGetMotorCodeAVACAsync(motor_code_av, null);
        }
        
        /// <remarks/>
        public void WSGetMotorCodeAVACAsync(string motor_code_av, object userState) {
            if ((this.WSGetMotorCodeAVACOperationCompleted == null)) {
                this.WSGetMotorCodeAVACOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSGetMotorCodeAVACOperationCompleted);
            }
            this.InvokeAsync("WSGetMotorCodeAVAC", new object[] {
                        motor_code_av}, this.WSGetMotorCodeAVACOperationCompleted, userState);
        }
        
        private void OnWSGetMotorCodeAVACOperationCompleted(object arg) {
            if ((this.WSGetMotorCodeAVACCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSGetMotorCodeAVACCompleted(this, new WSGetMotorCodeAVACCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetMakeCompletedEventHandler(object sender, WSGetMakeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetMakeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetMakeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetMakeYearCompletedEventHandler(object sender, WSGetMakeYearCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetMakeYearCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetMakeYearCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetModelCompletedEventHandler(object sender, WSGetModelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetModelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetModelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetModelDescriptionCompletedEventHandler(object sender, WSGetModelDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetModelDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetModelDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetCarInsuredAVCompletedEventHandler(object sender, WSGetCarInsuredAVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetCarInsuredAVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetCarInsuredAVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetMotorCodeACCompletedEventHandler(object sender, WSGetMotorCodeACCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetMotorCodeACCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetMotorCodeACCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetProvinceAddressCompletedEventHandler(object sender, WSGetProvinceAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetProvinceAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetProvinceAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetAmphurAddressCompletedEventHandler(object sender, WSGetAmphurAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetAmphurAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetAmphurAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetTumbonAddressCompletedEventHandler(object sender, WSGetTumbonAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetTumbonAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetTumbonAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetProvinceLicenseCompletedEventHandler(object sender, WSGetProvinceLicenseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetProvinceLicenseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetProvinceLicenseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetBeneficiaryCompletedEventHandler(object sender, WSGetBeneficiaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetBeneficiaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetBeneficiaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetCountryCompletedEventHandler(object sender, WSGetCountryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetCountryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetCountryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WSGetMotorCodeAVACCompletedEventHandler(object sender, WSGetMotorCodeAVACCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSGetMotorCodeAVACCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSGetMotorCodeAVACCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591